<a href="https://colab.research.google.com/github/PeteJoh/fpl-ai/blob/master/clean_fixtures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# MAKE SURE TO ENTER YEAR/PREVIOUS YEAR DETAILS AT THE START OF EACH SEASON
# MAKE SURE TO ENTER THE CORRECT GW TO BE ASSESSED - NEXT FIXTURES TO BE PLAYED - EVERY GAMEWEEK
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [2]:
seasons=["2020-21","2021-22","2022-23", "2023-24"]
unused_columns=["xP","opponent_team","expected_assists","expected_goal_involvements","expected_goals",
                "expected_goals_conceded","element_type_ex","team_h_score","team_a_score","element" , "round" ,"fixture","starts" ]
#stats that you want to use their values for the last few games to predict a

no_last_stats=3 #number of last gameweek stats to use for prediction

history_stats=["assists","bonus","bps","clean_sheets","creativity","goals_conceded","goals_scored","ict_index","influence","minutes",
               "own_goals","penalties_missed","penalties_saved","red_cards","saves","selected","threat","total_points","transfers_in","transfers_out","value","match_result","team Goal scored","team Goal conceded"]

last_features=[f"last {no_last_stats} {stat}" for stat in history_stats]

mean_features=["assists","bonus","bps","clean_sheets","creativity","goals_conceded",
     "goals_scored","ict_index","influence","minutes"
     ,"own_goals","penalties_missed","penalties_saved",
     "red_cards","saves","selected","threat","total_points"
     ,"transfers_in","transfers_out","value","match_result","team Goal scored","team Goal conceded"]

std_features=["bps","creativity","ict_index","influence","minutes","selected","threat","total_points","transfers_in","transfers_out","value"]



dropped_columns = [
    "season",
    "opponent",
    "match_result",
    "position",
    "assists",
    "penalties_missed",
    "bonus",
    "bps",
    "clean_sheets",
    "creativity",
    "goals_conceded",
    "goals_scored",
    "ict_index",
    "influence",
    "own_goals",
    "penalties_saved",
    "red_cards",
    "saves",
    "selected",
    "threat",
    "transfers_balance",
    "transfers_in",
    "transfers_out",
    "yellow_cards"
]  # "value",



leak_columns = [
    "name",
    "team",
]  # columns that shouldnt be used in training fir fear of data leakage



short_term_stats=3

team_features=["team Goal scored","team Goal conceded"]

In [3]:
#from config import *
import numpy as np
import pandas as pd
from scipy import stats


def split_test(data, gameweek):
    # print(data["GW"].value_counts())
    data_gw = data[data["GW"] == gameweek]
    data_other_gw = data[~(data["GW"] == gameweek)]
    return data_gw, data_other_gw


def check_win(df):
    list_win = []
    for index in df.index:
        result = (df["team_a_score"] - df["team_h_score"]).loc[index]
        is_home = df["was_home"].loc[index]
        if result == 0:
            list_win.append(1)
        elif result > 0 and is_home == True:
            list_win.append(0)
        elif result < 0 and is_home == True:
            list_win.append(3)
        elif result > 0 and is_home == False:
            list_win.append(3)
        elif result < 0 and is_home == False:
            list_win.append(0)
        else:
            list_win.append(-1)
    return list_win


def get_2020_21_season_pos(club):
    """get the position of the club in the 2020-21 season"""
    if club == "Man City":
        return 1
    elif club == "Man Utd":
        return 2
    elif club == "Liverpool":
        return 3
    elif club == "Chelsea":
        return 4
    elif club == "Leicester":
        return 5
    elif club == "West Ham":
        return 6
    elif club == "Spurs":
        return 7
    elif club == "Arsenal":
        return 8
    elif club == "Leeds":
        return 9
    elif club == "Everton":
        return 10
    elif club == "Aston Villa":
        return 11
    elif club == "Newcastle":
        return 12
    elif club == "Wolves":
        return 13
    elif club == "Crystal Palace":
        return 14
    elif club == "Southampton":
        return 15
    elif club == "Brighton":
        return 16
    elif club == "Burnley":
        return 17
    else:
        return 20


def get_2019_20_season_pos(club):
    """get the position of the club in the 2019-20 season"""
    if club == "Liverpool":
        return 1
    elif club == "Man City":
        return 2
    elif club == "Man Utd":
        return 3
    elif club == "Chelsea":
        return 4
    elif club == "Leicester":
        return 5
    elif club == "Spurs":
        return 6
    elif club == "Wolves":
        return 7
    elif club == "Arsenal":
        return 8
    elif club == "Sheffield Utd":
        return 9
    elif club == "Burnley":
        return 10
    elif club == "Southampton":
        return 11
    elif club == "Everton":
        return 12
    elif club == "Newcastle":
        return 13
    elif club == "Crystal Palace":
        return 14
    elif club == "Brighton":
        return 15
    elif club == "West Ham":
        return 16
    elif club == "Aston Villa":
        return 17
    else:
        return 20


def get_2021_22_season_pos(club):
    if club == "Man City":
        return 1
    elif club == "Liverpool":
        return 2
    elif club == "Chelsea":
        return 3
    elif club == "Spurs":
        return 4
    elif club == "Arsenal":
        return 5
    elif club == "Man Utd":
        return 6
    elif club == "West Ham":
        return 7
    elif club == "Leicester":
        return 8
    elif club == "Brighton":
        return 9
    elif club == "Wolves":
        return 10
    elif club == "Newcastle":
        return 11
    elif club == "Crystal Palace":
        return 12
    elif club == "Brentford":
        return 13
    elif club == "Aston Villa":
        return 14
    elif club == "Southampton":
        return 15
    elif club == "Everton":
        return 16
    elif club == "Leeds":
        return 17
    else:
        return 20


def get_2022_23_season_pos(club):
    if club == "Man City":
        return 1
    elif club == "Arsenal":
        return 2
    elif club == "Man Utd":
        return 3
    elif club == "Newcastle":
        return 4
    elif club == "Liverpool":
        return 5
    elif club == "Brighton":
        return 6
    elif club == "Aston Villa":
        return 7
    elif club == "Spurs":
        return 8
    elif club == "Brentford":
        return 9
    elif club == "Fulham":
        return 10
    elif club == "Crystal Palace":
        return 11
    elif club == "Chelsea":
        return 12
    elif club == "Wolves":
        return 13
    elif club == "West Ham":
        return 14
    elif club == "Bournemouth":
        return 15
    elif club == "Nott'm Forest":
        return 16
    elif club == "Everton":
        return 17
    else:
        return 20

def get_2023_24_season_pos(club):
    if club == "Man City":
        return 1
    elif club == "Arsenal":
        return 2
    elif club == "Liverpool":
        return 3
    elif club == "Aston Villa":
        return 4
    elif club == "Spurs":
        return 5
    elif club == "Chelsea":
        return 6
    elif club == "Newcastle":
        return 7
    elif club == "Man Utd":
        return 8
    elif club == "West Ham":
        return 9
    elif club == "Crystal Palace":
        return 10
    elif club == "Brighton":
        return 11
    elif club == "Bournemouth":
        return 12
    elif club == "Fulham":
        return 13
    elif club == "Wolves":
        return 14
    elif club == "Everton":
        return 15
    elif club == "Brentford":
        return 16
    elif club == "Nott'm Forest":
        return 17
    else:
        return 20


def get_last_season_pos(year):
    """get the function to get the last season position of a team at any year"""
    if year == "2020-21":
        return get_2019_20_season_pos
    elif year == "2021-22":
        return get_2020_21_season_pos
    elif year == "2022-23":
        return get_2021_22_season_pos
    elif year == "2023-24":
        return get_2022_23_season_pos
    elif year == "2024-25":
        return get_2023_24_season_pos


def remove_neg(val):
    if val > 0:
        return val
    else:
        return -val


def deque_and_queue(stats, value):
    # if -1 in stats:
    #  return stats
    # deque
    stats = stats[1:]
    stats.append(value)
    return stats


def get_last_stats(data, stat, name, no_last_stats=3):
    name_df = data[data["name"] == name]
    seasons = ["2020-21", "2021-22", "2022-23", "2023-24"]
    name_df_dict = {}
    for season in seasons:
        name_df_season = name_df[name_df["season"] == season]
        list_stats = []
        stats_x = []
        for value in name_df_season[stat]:
            if len(stats_x) < no_last_stats:
                list_stats.append(np.array(stats_x))
                stats_x.append(value)
            else:
                list_stats.append(np.array(stats_x))
                stats_x = deque_and_queue(stats_x, value)
        name_df_season[f"last {no_last_stats} {stat}"] = list_stats
        name_df_dict[season] = name_df_season
    return pd.concat(name_df_dict.values())


def get_all_players_last_stats(data, stat, no_last_stats=3):
    players_df = []
    for player in data["name"].unique():
        data_player = get_last_stats(data, stat, player, no_last_stats)
        players_df.append(data_player)
    # print(pd.concat(players_df))
    return pd.concat(players_df)


def get_last_stats_test(data, stat, name, no_last_stats=3):
    name_df = data[data["name"] == name]
    list_stats = []
    stats_x = []
    for value in name_df[stat]:
        if len(stats_x) < no_last_stats:
            list_stats.append(np.array(stats_x))
            stats_x.append(value)
        else:
            list_stats.append(np.array(stats_x))
            stats_x = deque_and_queue(stats_x, value)
    name_df[f"last {no_last_stats} {stat}"] = list_stats
    return name_df


def get_players_last_stats_test(data, stat, no_last_stats=short_term_stats):
    players_df = []
    for player in data["name"].unique():
        data_player = get_last_stats_test(data, stat, player, no_last_stats)
        players_df.append(data_player)
    # print(pd.concat(players_df))
    return pd.concat(players_df)

def get_all_stats_test(data, stat, name):
    name_df = data[data["name"] == name]
    list_stats = []
    stats_x = []
    for value in name_df[stat]:
        list_stats.append(np.array(stats_x))
        stats_x.append(value)
    name_df[f"all {stat}"] = list_stats
    return name_df


def get_players_all_stats_test(data, stat):
    players_df = []
    for player in data["name"].unique():
        data_player = get_all_stats_test(data, stat, player)
        players_df.append(data_player)
    # print(pd.concat(players_df))
    return pd.concat(players_df)

def convert_minutes(val):
    """CONVERTS MINUTES TO A CATEGORICAL OUTPUT"""
    if val > 10:
        return 1
    else:
        return 0


def find_mode(vals):
    """find the mode of vals"""
    try:
        if -1 in vals:
            return -1
        return stats.mode(vals)[0][0]
    except IndexError:
        return np.nan


def find_mean(vals):
    """find the mean of vals"""
    try:
        if -1 in vals:
            return -1
        return np.mean(vals)
    except:
        return np.nan


def find_max(vals):
    """find the maximum of vals"""
    try:
        if -1 in vals:
            return -1
        return np.max(vals)
    except:
        return np.nan


def find_std(vals):
    """find the standard deviation of vals"""
    try:
        if -1 in vals:
            return -1
        return np.std(vals)
    except:
        return np.nan


def find_value_count(vals, to_count):
    """find the number of times to_count appears in vals"""
    try:
        if -1 in vals:
            return -1
        values, count = np.unique(vals, return_counts=True)
        index = np.where(values == to_count)[0][0]
        return count[index]

    except:
        return -2


def get_opp_team(data):
    """get the opponent team for each player"""
    opp_teams = []
    home_teams = data["home_team"]
    away_teams = data["away_team"]
    my_teams = data["team"]
    for id in data.index:
        my_team = my_teams.iloc[id]
        home_team = home_teams.iloc[id]
        away_team = away_teams.iloc[id]
        if my_team == home_team:
            opp_teams.append(away_team)
        else:
            opp_teams.append(home_team)
    return opp_teams




def create_features(data, mean_features, std_features):
    for mean_feature in mean_features:
        print(mean_feature)
        data[f"mean {mean_feature} {no_last_stats}"] = [
            find_mean(values) for values in data[f"last {no_last_stats} {mean_feature}"]
        ]
        data[f"mean {mean_feature} all"] = [
            find_mean(values) for values in data[f"all {mean_feature}"]
        ]
        #data[f"mean {mean_feature} all"]= data[f"mean {mean_feature} all"]/data["GW"]
    for std_feature in std_features:
        print(std_feature)
        data[f"std {std_feature} {no_last_stats}"] = [
            find_std(values) for values in data[f"last {no_last_stats} {std_feature}"]
        ]
    return data

In [4]:


import pandas as pd
import numpy as np
#from config import unused_columns, history_stats, no_last_stats
import warnings

warnings.filterwarnings("ignore")


def calculate_ratio_team_value(name, df=None):
    """Calculate the ratio of player value to team value"""
    team = df[df["name"] == name]["team"].iloc[0]
    total_value = df[df["team"] == team]["value"].sum()
    value = df[df["name"] == name]["value"].iloc[0]
    return value * 100 / total_value


def calculate_position_rank(name, df=None):
    """Calculate the number of players with a higher  value"""
    value = df[df["name"] == name]["value"].iloc[0]
    position = df[df["name"] == name]["position"].iloc[0]
    team = df[df["name"] == name]["team"].iloc[0]
    return df[
        (df["value"] > value) & (df["position"] == position) & (df["team"] == team)
    ]["value"].shape[0]


gameweek = 10
#********************ENTER NEXT GW TO BE PLAYED*******************************
old_gameweek_results = []
for i in range(1, gameweek):
    result = pd.read_csv(f"/content/gdrive/MyDrive/fplpredict/datasets/2024-25/results/GW{i}.csv", index_col=0)
    result.columns = [
        "element",
        "fixture",
        "opponent_team",
        "total_points",
        "was_home",
        "kickoff_time",
        "team_h_score",
        "team_a_score",
        "round",
        "minutes",
        "goals_scored",
        "assists",
        "clean_sheets",
        "goals_conceded",
        "own_goals",
        "penalties_saved",
        "penalties_missed",
        "yellow_cards",
        "red_cards",
        "saves",
        "bonus",
        "bps",
        "influence",
        "creativity",
        "threat",
        "ict_index",
        "starts",
        "expected_goals",
        "expected_assists",
        "expected_goal_involvements",
        "expected_goals_conceded",
        "value",
        "transfers_balance",
        "selected",
        "transfers_in",
        "transfers_out",
        "id",
        "name",
        "cost",
        "position",
        "home_team",
        "away_team",
        "team",
    ]
    year = "2024-25"
    previous_year = "2023-24"
    result["xP"] = 0
    result["GW"] = i
    result["match_result"] = check_win(result)
    result["opponent"] = get_opp_team(result)
    print(result.shape)
    result["last_season_position"] = result["team"].apply(get_last_season_pos(year))
    result["opponent_last_season_position"] = result["opponent"].apply(
        get_last_season_pos(year)
    )
    result["percent_value"] = result["name"].apply(
        calculate_ratio_team_value, args=(result,)
    )
    result["position rank"] = result["name"].apply(
        calculate_position_rank, args=(result,)
    )

    player_prev_stats = pd.read_csv(
        f"https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/{previous_year}/cleaned_players.csv"
    )
    player_prev_stats["name"] = (
        player_prev_stats["first_name"] + " " + player_prev_stats["second_name"]
    )
    player_prev_stats.drop(["first_name", "second_name"], axis=1, inplace=True)
    player_prev_stats.columns = player_prev_stats.columns + "_ex"
    result = pd.merge(
        result, player_prev_stats, left_on="name", right_on="name_ex", how="left"
    )
    result_home=result[result["was_home"]==True]
    result_away=result[result["was_home"]==False]
    result_home["team Goal scored"]=result_home["team_h_score"]
    result_home["team Goal conceded"]=result_home["team_a_score"]
    result_away["team Goal conceded"]=result_away["team_h_score"]
    result_away["team Goal scored"]=result_away["team_a_score"]
    result=pd.concat([result_home,result_away])
    result.drop(unused_columns, axis=1, inplace=True)
    old_gameweek_results.append(result)
    print(i)

# print(old_gameweek_results[0]["opponent"].value_counts())
current_fixture = pd.read_csv(
    f"/content/gdrive/MyDrive/fplpredict/datasets/2024-25/fixtures/GW{gameweek}.csv", index_col=0
)
current_fixture.columns = [
    "id",
    "name",
    "value",
    "position",
    "home_team",
    "away_team",
    "kickoff_time",
    "was_home",
    "team",
]


current_fixture["opponent"] = get_opp_team(current_fixture)
# print(current_fixture["opponent"].value_counts())
current_fixture["last_season_position"] = current_fixture["team"].apply(
    get_last_season_pos(year)
)
current_fixture["opponent_last_season_position"] = current_fixture["opponent"].apply(
    get_last_season_pos(year)
)
current_fixture["percent_value"] = current_fixture["name"].apply(
    calculate_ratio_team_value, args=(current_fixture,)
)
current_fixture["position rank"] = current_fixture["name"].apply(
    calculate_position_rank, args=(current_fixture,)
)


# check_win not posible because it's only fixtures we have for now
# merge last season data
player_prev_stats = pd.read_csv(
    f"https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/{previous_year}/cleaned_players.csv"
)

player_prev_stats["name"] = (
    player_prev_stats["first_name"] + " " + player_prev_stats["second_name"]
)

player_prev_stats.drop(["first_name", "second_name"], axis=1, inplace=True)
player_prev_stats.columns = player_prev_stats.columns + "_ex"
current_fixture = pd.merge(
    current_fixture, player_prev_stats, left_on="name", right_on="name_ex", how="left"
)

current_fixture["GW"] = gameweek
old_gameweek_results.append(current_fixture)
data = pd.concat(old_gameweek_results)

data = data.sort_values(["name", "kickoff_time"], ascending=True)


data["season"] = year
data.drop(["name_ex", "id", "home_team", "away_team"], axis=1, inplace=True)

for stat in history_stats:
    print(stat)
    data = get_players_last_stats_test(data, stat)
    data = get_players_all_stats_test(data, stat)

data = create_features(data, mean_features, std_features)
data.drop(
    [f"last {no_last_stats} {stat}" for stat in history_stats], axis=1, inplace=True
)
data.drop([f"all {stat}" for stat in history_stats],axis=1,inplace=True)
data["ratio_goal_scored 3"]=((data["mean goals_scored 3"]/data["mean team Goal scored 3"]).replace(np.inf, 0))*100
data["ratio_goal_scored all"]=((data["mean goals_scored all"]/data["mean team Goal scored all"]).replace(np.inf, 0))*100

(670, 47)
1
(667, 47)
2
(666, 47)
3
(664, 47)
4
(661, 47)
5
(659, 47)
6
(648, 47)
7
(627, 47)
8
(616, 47)
9
assists
bonus
bps
clean_sheets
creativity
goals_conceded
goals_scored
ict_index
influence
minutes
own_goals
penalties_missed
penalties_saved
red_cards
saves
selected
threat
total_points
transfers_in
transfers_out
value
match_result
team Goal scored
team Goal conceded
assists
bonus
bps
clean_sheets
creativity
goals_conceded
goals_scored
ict_index
influence
minutes
own_goals
penalties_missed
penalties_saved
red_cards
saves
selected
threat
total_points
transfers_in
transfers_out
value
match_result
team Goal scored
team Goal conceded
bps
creativity
ict_index
influence
minutes
selected
threat
total_points
transfers_in
transfers_out
value

In [5]:
#add opponent stats for gameweeks
list_data_gw=[]
for GW in range(1,gameweek + 1):

    data_gw=data[data["GW"]==GW].sort_values(by="mean team Goal scored all", ascending=False)
    data_opponent=data_gw.drop_duplicates(subset="team")[['team','mean team Goal scored 3','mean team Goal conceded 3','mean team Goal scored all','mean team Goal conceded all',"mean match_result all"]]
    print(data_opponent.reset_index().drop("index",axis=1))
    #print(data_gw.shape)
    data_opponent.columns=['opponent','opp mean team Goal scored 3','opp mean team Goal conceded 3','opp mean team Goal scored all','opp mean team Goal conceded all',"opp mean match_result all"]
    #print(data_opponent.shape)
    data_gw=pd.merge(data_gw,data_opponent,on="opponent",how="left")
    list_data_gw.append(data_gw)

              team  mean team Goal scored 3  mean team Goal conceded 3  \
0         West Ham                      NaN                        NaN
1        Brentford                      NaN                        NaN
2      Southampton                      NaN                        NaN
3          Everton                      NaN                        NaN
4        Leicester                      NaN                        NaN
5      Bournemouth                      NaN                        NaN
6         Brighton                      NaN                        NaN
7   Crystal Palace                      NaN                        NaN
8           Fulham                      NaN                        NaN
9          Man Utd                      NaN                        NaN
10           Spurs                      NaN                        NaN
11   Nott'm Forest                      NaN                        NaN
12       Newcastle                      NaN                        NaN
13       Liverpool                      NaN                        NaN
14         Chelsea                      NaN                        NaN
15          Wolves                      NaN                        NaN
16         Ipswich                      NaN                        NaN
17     Aston Villa                      NaN                        NaN
18         Arsenal                      NaN                        NaN
19        Man City                      NaN                        NaN

    mean team Goal scored all  mean team Goal conceded all  \
0                         NaN                          NaN
1                         NaN                          NaN
2                         NaN                          NaN
3                         NaN                          NaN
4                         NaN                          NaN
5                         NaN                          NaN
6                         NaN                          NaN
7                         NaN                          NaN
8                         NaN                          NaN
9                         NaN                          NaN
10                        NaN                          NaN
11                        NaN                          NaN
12                        NaN                          NaN
13                        NaN                          NaN
14                        NaN                          NaN
15                        NaN                          NaN
16                        NaN                          NaN
17                        NaN                          NaN
18                        NaN                          NaN
19                        NaN                          NaN

    mean match_result all
0                     NaN
1                     NaN
2                     NaN
3                     NaN
4                     NaN
5                     NaN
6                     NaN
7                     NaN
8                     NaN
9                     NaN
10                    NaN
11                    NaN
12                    NaN
13                    NaN
14                    NaN
15                    NaN
16                    NaN
17                    NaN
18                    NaN
19                    NaN
              team  mean team Goal scored 3  mean team Goal conceded 3  \
0          Chelsea                      6.0                        2.0
1          Arsenal                      4.0                        2.0
2         Man City                      4.0                        1.0
3         Brighton                      3.0                        0.0
4        Liverpool                      3.0                        0.0
5          Man Utd                      3.0                        0.0
6        Brentford                      3.0                        1.0
7      Aston Villa                      3.0                        2.0
8   Crystal Palace                      2.0                        0.0
9           Fulham                      2.0                        1.0
10         Everton                      2.0                        3.0
11   Nott'm Forest                      2.0                        1.0
12     Southampton                      2.0                        0.0
13     Bournemouth                      1.0                        1.0
14           Spurs                      1.0                        1.0
15       Leicester                      1.0                        1.0
16       Newcastle                      1.0                        0.0
17        West Ham                      1.0                        3.0
18          Wolves                      1.0                        2.0
19         Ipswich                      1.0                        1.0

    mean team Goal scored all  mean team Goal conceded all  \
0                         6.0                          2.0
1                         4.0                          2.0
2                         4.0                          1.0
3                         3.0                          0.0
4                         3.0                          0.0
5                         3.0                          0.0
6                         3.0                          1.0
7                         3.0                          2.0
8                         2.0                          0.0
9                         2.0                          1.0
10                        2.0                          3.0
11                        2.0                          1.0
12                        2.0                          0.0
13                        1.0                          1.0
14                        1.0                          1.0
15                        1.0                          1.0
16                        1.0                          0.0
17                        1.0                          3.0
18                        1.0                          2.0
19                        1.0                          1.0

    mean match_result all
0                     3.0
1                     3.0
2                     3.0
3                     3.0
4                     3.0
5                     3.0
6                     3.0
7                     3.0
8                     3.0
9                     3.0
10                    0.0
11                    3.0
12                    3.0
13                    1.0
14                    1.0
15                    1.0
16                    3.0
17                    0.0
18                    0.0
19                    1.0
              team  mean team Goal scored 3  mean team Goal conceded 3  \
0          Arsenal                      3.5                        1.5
1         Man City                      3.5                        1.0
2          Chelsea                      3.5                        1.5
3          Everton                      3.0                        2.0
4   Crystal Palace                      3.0                        2.0
5      Bournemouth                      3.0                        2.0
6      Aston Villa                      3.0                        1.5
7            Spurs                      2.5                        0.5
8         Brighton                      2.5                        0.5
9        Liverpool                      2.5                        0.5
10          Wolves                      2.0                        3.5
11     Southampton                      2.0                        0.0
12          Fulham                      2.0                        0.0
13       Brentford                      2.0                        1.5
14        West Ham                      1.5                        1.0
15   Nott'm Forest                      1.5                        0.5
16         Man Utd                      1.5                        0.0
17       Leicester                      1.5                        2.0
18       Newcastle                      1.0                        0.5
19         Ipswich                      1.0                        2.5

    mean team Goal scored all  mean team Goal conceded all  \
0                         3.5                          1.5
1                         3.5                          1.0
2                         3.5                          1.5
3                         3.0                          2.0
4                         3.0                          2.0
5                         3.0                          2.0
6                         3.0                          1.5
7                         2.5                          0.5
8                         2.5                          0.5
9                         2.5                          0.5
10                        2.0                          3.5
11                        2.0                          0.0
12                        2.0                          0.0
13                        2.0                          1.5
14                        1.5                          1.0
15                        1.5                          0.5
16                        1.5                          0.0
17                        1.5                          2.0
18                        1.0                          0.5
19                        1.0                          2.5

    mean match_result all
0                     3.0
1                     3.0
2                     2.0
3                     1.5
4                     1.5
5                     1.5
6                     3.0
7                     2.0
8                     3.0
9                     3.0
10                    0.0
11                    3.0
12                    3.0
13                    1.5
14                    1.5
15                    3.0
16                    2.0
17                    0.5
18                    2.0
19                    0.5
              team  mean team Goal scored 3  mean team Goal conceded 3  \
0         Man City                 3.000000                   0.666667
1      Bournemouth                 3.000000                   2.000000
2      Aston Villa                 2.666667                   1.333333
3          Everton                 2.666667                   2.333333
4          Chelsea                 2.666667                   1.000000
5        Liverpool                 2.333333                   0.000000
6          Arsenal                 2.333333                   1.666667
7        Brentford                 2.333333                   2.333333
8   Crystal Palace                 2.333333                   1.666667
9            Spurs                 2.000000                   1.000000
10        Brighton                 2.000000                   0.666667
11     Southampton                 1.666667                   1.000000
12          Wolves                 1.666667                   3.000000
13          Fulham                 1.666667                   0.333333
14        West Ham                 1.333333                   1.666667
15       Newcastle                 1.333333                   0.666667
16   Nott'm Forest                 1.333333                   0.666667
17       Leicester                 1.333333                   1.666667
18         Man Utd                 1.000000                   1.000000
19         Ipswich                 0.666667                   2.333333

    mean team Goal scored all  mean team Goal conceded all  \
0                    3.000000                     0.666667
1                    3.000000                     2.000000
2                    2.666667                     1.333333
3                    2.666667                     2.333333
4                    2.666667                     1.000000
5                    2.333333                     0.000000
6                    2.333333                     1.666667
7                    2.333333                     2.333333
8                    2.333333                     1.666667
9                    2.000000                     1.000000
10                   2.000000                     0.666667
11                   1.666667                     1.000000
12                   1.666667                     3.000000
13                   1.666667                     0.333333
14                   1.333333                     1.666667
15                   1.333333                     0.666667
16                   1.333333                     0.666667
17                   1.333333                     1.666667
18                   1.000000                     1.000000
19                   0.666667                     2.333333

    mean match_result all
0                3.000000
1                2.000000
2                3.000000
3                1.000000
4                2.333333
5                3.000000
6                2.000000
7                1.333333
8                1.333333
9                1.333333
10               2.333333
11               2.000000
12               0.000000
13               2.333333
14               1.000000
15               2.333333
16               2.333333
17               0.666667
18               1.333333
19               0.333333
              team  mean team Goal scored 3  mean team Goal conceded 3  \
0          Chelsea                 1.666667                   0.333333
1         Man City                 3.000000                   1.000000
2          Everton                 3.333333                   2.666667
3      Aston Villa                 2.666667                   1.666667
4          Arsenal                 3.000000                   1.666667
5   Crystal Palace                 3.000000                   1.666667
6      Bournemouth                 3.000000                   1.666667
7        Liverpool                 1.666667                   0.666667
8        Brentford                 2.333333                   2.000000
9           Fulham                 1.666667                   1.000000
10       Newcastle                 1.666667                   1.000000
11           Spurs                 1.666667                   1.000000
12        Brighton                 1.000000                   0.666667
13          Wolves                 1.666667                   3.333333
14        West Ham                 1.666667                   1.666667
15       Leicester                 1.666667                   2.333333
16         Man Utd                 1.333333                   1.666667
17   Nott'm Forest                 1.000000                   0.333333
18     Southampton                 1.000000                   2.000000
19         Ipswich                 1.000000                   1.000000

    mean team Goal scored all  mean team Goal conceded all  \
0                        2.75                         0.75
1                        2.75                         0.75
2                        2.50                         2.50
3                        2.50                         1.50
4                        2.50                         1.25
5                        2.25                         1.75
6                        2.25                         1.75
7                        2.00                         0.50
8                        2.00                         2.25
9                        1.75                         1.00
10                       1.50                         0.75
11                       1.50                         1.00
12                       1.50                         0.50
13                       1.50                         3.00
14                       1.50                         1.50
15                       1.50                         2.25
16                       1.25                         1.25
17                       1.25                         0.50
18                       1.25                         1.50
19                       1.00                         1.00

    mean match_result all
0                    2.50
1                    3.00
2                    0.75
3                    2.50
4                    2.50
5                    1.25
6                    1.50
7                    2.25
8                    1.00
9                    2.00
10                   2.50
11                   1.00
12                   2.00
13                   0.00
14                   1.25
15                   0.50
16                   1.50
17                   2.50
18                   1.50
19                   1.00
              team  mean team Goal scored 3  mean team Goal conceded 3  \
0          Chelsea                 2.666667                   0.666667
1         Man City                 2.333333                   1.333333
2        Brentford                 2.333333                   2.333333
3          Arsenal                 3.000000                   1.666667
4          Everton                 1.666667                   2.333333
5      Aston Villa                 1.666667                   1.000000
6        Liverpool                 2.000000                   0.333333
7            Spurs                 1.333333                   1.333333
8   Crystal Palace                 1.000000                   1.000000
9           Fulham                 1.666667                   1.000000
10     Bournemouth                 1.000000                   2.000000
11        Brighton                 1.000000                   1.000000
12       Newcastle                 1.666667                   1.666667
13          Wolves                 1.666667                   3.333333
14   Nott'm Forest                 1.333333                   1.000000
15        West Ham                 1.666667                   1.666667
16       Leicester                 1.333333                   1.666667
17     Southampton                 0.666667                   2.333333
18         Man Utd                 1.000000                   1.000000
19         Ipswich                 1.333333                   2.333333

    mean team Goal scored all  mean team Goal conceded all  \
0                         3.0                          1.0
1                         2.6                          1.0
2                         2.2                          2.0
3                         2.2                          1.2
4                         2.2                          2.2
5                         2.2                          1.2
6                         2.0                          0.2
7                         1.8                          1.0
8                         1.8                          1.4
9                         1.8                          0.6
10                        1.8                          2.0
11                        1.6                          0.8
12                        1.4                          1.2
13                        1.4                          2.6
14                        1.4                          1.0
15                        1.4                          1.8
16                        1.4                          1.8
17                        1.2                          1.4
18                        1.0                          1.0
19                        1.0                          1.6

    mean match_result all
0                     2.6
1                     2.6
2                     1.4
3                     2.2
4                     0.8
5                     2.2
6                     2.4
7                     1.4
8                     1.2
9                     2.2
10                    1.2
11                    1.8
12                    2.0
13                    0.2
14                    1.6
15                    1.0
16                    1.0
17                    1.4
18                    1.4
19                    0.8
              team  mean team Goal scored 3  mean team Goal conceded 3  \
0          Chelsea                 2.666667                   1.000000
1         Man City                 2.000000                   1.666667
2          Arsenal                 2.333333                   1.333333

In [6]:
data=pd.concat(list_data_gw)
data=data.drop_duplicates(["GW","team","opponent","name","kickoff_time"])

In [7]:
data.shape

(6548, 122)

In [8]:
5398+509

5907

In [9]:
data.shape

(6548, 122)

In [10]:
# save cleaned files
for i in range(1, gameweek + 1):
    data_gw = data[data["GW"] == i]
    data_gw.to_csv(f"/content/gdrive/MyDrive/fplpredict/cleaned_dataset/2024-25/GW{i}.csv")
    print(i)

1
2
3
4
5
6
7
8
9
10

# DEBUGGING ERRORS

In [11]:
list(data.columns)

['total_points',
 'was_home',
 'kickoff_time',
 'minutes',
 'goals_scored',
 'assists',
 'clean_sheets',
 'goals_conceded',
 'own_goals',
 'penalties_saved',
 'penalties_missed',
 'yellow_cards',
 'red_cards',
 'saves',
 'bonus',
 'bps',
 'influence',
 'creativity',
 'threat',
 'ict_index',
 'value',
 'transfers_balance',
 'selected',
 'transfers_in',
 'transfers_out',
 'name',
 'cost',
 'position',
 'team',
 'GW',
 'match_result',
 'opponent',
 'last_season_position',
 'opponent_last_season_position',
 'percent_value',
 'position rank',
 'goals_scored_ex',
 'assists_ex',
 'total_points_ex',
 'minutes_ex',
 'goals_conceded_ex',
 'creativity_ex',
 'influence_ex',
 'threat_ex',
 'bonus_ex',
 'bps_ex',
 'ict_index_ex',
 'clean_sheets_ex',
 'red_cards_ex',
 'yellow_cards_ex',
 'selected_by_percent_ex',
 'now_cost_ex',
 'team Goal scored',
 'team Goal conceded',
 'element_type_ex',
 'season',
 'mean assists 3',
 'mean assists all',
 'mean bonus 3',
 'mean bonus all',
 'mean bps 3',
 'mean bps all',
 'mean clean_sheets 3',
 'mean clean_sheets all',
 'mean creativity 3',
 'mean creativity all',
 'mean goals_conceded 3',
 'mean goals_conceded all',
 'mean goals_scored 3',
 'mean goals_scored all',
 'mean ict_index 3',
 'mean ict_index all',
 'mean influence 3',
 'mean influence all',
 'mean minutes 3',
 'mean minutes all',
 'mean own_goals 3',
 'mean own_goals all',
 'mean penalties_missed 3',
 'mean penalties_missed all',
 'mean penalties_saved 3',
 'mean penalties_saved all',
 'mean red_cards 3',
 'mean red_cards all',
 'mean saves 3',
 'mean saves all',
 'mean selected 3',
 'mean selected all',
 'mean threat 3',
 'mean threat all',
 'mean total_points 3',
 'mean total_points all',
 'mean transfers_in 3',
 'mean transfers_in all',
 'mean transfers_out 3',
 'mean transfers_out all',
 'mean value 3',
 'mean value all',
 'mean match_result 3',
 'mean match_result all',
 'mean team Goal scored 3',
 'mean team Goal scored all',
 'mean team Goal conceded 3',
 'mean team Goal conceded all',
 'std bps 3',
 'std creativity 3',
 'std ict_index 3',
 'std influence 3',
 'std minutes 3',
 'std selected 3',
 'std threat 3',
 'std total_points 3',
 'std transfers_in 3',
 'std transfers_out 3',
 'std value 3',
 'ratio_goal_scored 3',
 'ratio_goal_scored all',
 'opp mean team Goal scored 3',
 'opp mean team Goal conceded 3',
 'opp mean team Goal scored all',
 'opp mean team Goal conceded all',
 'opp mean match_result all']

In [12]:
for GW in range(1,gameweek + 1):
  print(f"GW{GW}")
  print(data[data["GW"]==GW]["team"].shape)

GW1
(670,)
GW2
(667,)
GW3
(666,)
GW4
(664,)
GW5
(661,)
GW6
(659,)
GW7
(648,)
GW8
(627,)
GW9
(616,)
GW10
(670,)

In [13]:
for GW in range(1,gameweek + 1):
  print(f"GW{GW}")
  print(len(data[data["GW"]==GW]["team"].unique()))
  print(data[data["GW"]==GW].drop_duplicates(subset="team")[["team","opponent","last_season_position","mean team Goal scored all","opp mean team Goal scored all"]].reset_index().drop("index",axis=1))#.sort_values("last_season_position"))
  print("\n\n")
  #.sort_values(by="mean team Goal scored all", ascending=False)

GW1
20
              team        opponent  last_season_position  \
0         West Ham   Nott'm Forest                     9
1        Brentford          Fulham                    16
2      Southampton         Everton                    20
3          Everton     Southampton                    15
4        Leicester         Ipswich                    20
5      Bournemouth        Man City                    12
6         Brighton       Liverpool                    11
7   Crystal Palace          Wolves                    10
8           Fulham       Brentford                    13
9          Man Utd         Chelsea                     8
10           Spurs     Aston Villa                     5
11   Nott'm Forest        West Ham                    17
12       Newcastle         Arsenal                     7
13       Liverpool        Brighton                     3
14         Chelsea         Man Utd                     6
15          Wolves  Crystal Palace                    14
16         Ipswich       Leicester                    20
17     Aston Villa           Spurs                     4
18         Arsenal       Newcastle                     2
19        Man City     Bournemouth                     1

    mean team Goal scored all  opp mean team Goal scored all
0                         NaN                            NaN
1                         NaN                            NaN
2                         NaN                            NaN
3                         NaN                            NaN
4                         NaN                            NaN
5                         NaN                            NaN
6                         NaN                            NaN
7                         NaN                            NaN
8                         NaN                            NaN
9                         NaN                            NaN
10                        NaN                            NaN
11                        NaN                            NaN
12                        NaN                            NaN
13                        NaN                            NaN
14                        NaN                            NaN
15                        NaN                            NaN
16                        NaN                            NaN
17                        NaN                            NaN
18                        NaN                            NaN
19                        NaN                            NaN



GW2
20
              team        opponent  last_season_position  \
0          Chelsea         Man Utd                     6
1          Arsenal       Newcastle                     2
2         Man City     Bournemouth                     1
3         Brighton       Liverpool                    11
4        Liverpool        Brighton                     3
5          Man Utd         Chelsea                     8
6        Brentford          Fulham                    16
7      Aston Villa           Spurs                     4
8   Crystal Palace          Wolves                    10
9           Fulham       Brentford                    13
10         Everton     Southampton                    15
11   Nott'm Forest        West Ham                    17
12     Southampton         Everton                    20
13     Bournemouth        Man City                    12
14           Spurs     Aston Villa                     5
15       Leicester         Ipswich                    20
16       Newcastle         Arsenal                     7
17        West Ham   Nott'm Forest                     9
18          Wolves  Crystal Palace                    14
19         Ipswich       Leicester                    20

    mean team Goal scored all  opp mean team Goal scored all
0                         6.0                            3.0
1                         4.0                            1.0
2                         4.0                            1.0
3                         3.0                            3.0
4                         3.0                            3.0
5                         3.0                            6.0
6                         3.0                            2.0
7                         3.0                            1.0
8                         2.0                            1.0
9                         2.0                            3.0
10                        2.0                            2.0
11                        2.0                            1.0
12                        2.0                            2.0
13                        1.0                            4.0
14                        1.0                            3.0
15                        1.0                            1.0
16                        1.0                            4.0
17                        1.0                            2.0
18                        1.0                            2.0
19                        1.0                            1.0



GW3
20
              team        opponent  last_season_position  \
0          Arsenal       Newcastle                     2
1         Man City     Bournemouth                     1
2          Chelsea         Man Utd                     6
3          Everton     Southampton                    15
4   Crystal Palace          Wolves                    10
5      Bournemouth        Man City                    12
6      Aston Villa           Spurs                     4
7            Spurs     Aston Villa                     5
8         Brighton       Liverpool                    11
9        Liverpool        Brighton                     3
10          Wolves  Crystal Palace                    14
11     Southampton         Everton                    20
12          Fulham       Brentford                    13
13       Brentford          Fulham                    16
14        West Ham   Nott'm Forest                     9
15   Nott'm Forest        West Ham                    17
16         Man Utd         Chelsea                     8
17       Leicester         Ipswich                    20
18       Newcastle         Arsenal                     7
19         Ipswich       Leicester                    20

    mean team Goal scored all  opp mean team Goal scored all
0                         3.5                            1.0
1                         3.5                            3.0
2                         3.5                            1.5
3                         3.0                            2.0
4                         3.0                            2.0
5                         3.0                            3.5
6                         3.0                            2.5
7                         2.5                            3.0
8                         2.5                            2.5
9                         2.5                            2.5
10                        2.0                            3.0
11                        2.0                            3.0
12                        2.0                            2.0
13                        2.0                            2.0
14                        1.5                            1.5
15                        1.5                            1.5
16                        1.5                            3.5
17                        1.5                            1.0
18                        1.0                            3.5
19                        1.0                            1.5



GW4
20
              team        opponent  last_season_position  \
0         Man City     Bournemouth                     1
1      Bournemouth        Man City                    12
2      Aston Villa           Spurs                     4
3          Everton     Southampton                    15
4          Chelsea         Man Utd                     6
5        Liverpool        Brighton                     3
6          Arsenal       Newcastle                     2
7        Brentford          Fulham                    16
8   Crystal Palace          Wolves                    10
9            Spurs     Aston Villa                     5
10        Brighton       Liverpool                    11
11     Southampton         Everton                    20
12          Wolves  Crystal Palace                    14
13          Fulham       Brentford                    13
14        West Ham   Nott'm Forest                     9
15       Newcastle         Arsenal                     7
16   Nott'm Forest        West Ham                    17
17       Leicester         Ipswich                    20
18         Man Utd         Chelsea                     8
19         Ipswich       Leicester                    20

    mean team Goal scored all  opp mean team Goal scored all
0                    3.000000                       3.000000
1                    3.000000                       3.000000
2                    2.666667                       2.000000
3                    2.666667                       1.666667
4                    2.666667                       1.000000
5                    2.333333                       2.000000
6                    2.333333                       1.333333
7                    2.333333                       1.666667
8                    2.333333                       1.666667
9                    2.000000                       2.666667
10                   2.000000                       2.333333
11                   1.666667                       2.666667
12                   1.666667                       2.333333
13                   1.666667                       2.333333
14                   1.333333                       1.333333
15                   1.333333                       2.333333
16                   1.333333                       1.333333
17                   1.333333                       0.666667
18                   1.000000                       2.666667
19                   0.666667                       1.333333



GW5
20
              team        opponent  last_season_position  \
0          Chelsea         Man Utd                     6
1         Man City     Bournemouth                     1
2          Everton     Southampton                    15
3      Aston Villa           Spurs                     4
4          Arsenal       Newcastle                     2
5   Crystal Palace          Wolves                    10
6      Bournemouth        Man City                    12
7        Liverpool        Brighton                     3
8        Brentford          Fulham                    16
9           Fulham       Brentford                    13
10       Newcastle         Arsenal                     7
11           Spurs     Aston Villa                     5
12        Brighton       Liverpool                    11
13          Wolves  Crystal Palace                    14
14        West Ham   Nott'm Forest                     9
15       Leicester         Ipswich                    20
16         Man Utd         Chelsea                     8
17   Nott'm Forest        West Ham                    17
18     Southampton         Everton                    20
19         Ipswich       Leicester                    20

    mean team Goal scored all  opp mean team Goal scored all
0                        2.75                           1.25
1                        2.75                           2.25
2                        2.50                           1.25
3                        2.50                           1.50
4                        2.50                           1.50
5                        2.25                           1.50
6                        2.25                           2.75
7                        2.00                           1.50
8                        2.00                           1.75
9                        1.75                           2.00
10                       1.50                           2.50
11                       1.50                           2.50
12                       1.50                           2.00
13                       1.50                           2.25
14                       1.50                           1.25
15                       1.50                           1.00
16                       1.25                           2.75
17                       1.25                           1.50
18                       1.25                           2.50
19                       1.00                           1.50



GW6
20
              team        opponent  last_season_position  \
0          Chelsea   Nott'm Forest                     6
1         Man City          Fulham                     1
2        Brentford          Wolves                    16
3          Arsenal     Southampton                     2
4          Everton       Newcastle                    15
5      Aston Villa         Man Utd                     4
6        Liverpool  Crystal Palace                     3
7            Spurs        Brighton                     5
8   Crystal Palace       Liverpool                    10
9           Fulham        Man City                    13
10     Bournemouth     Southampton                    12
11        Brighton           Spurs                    11
12       Newcastle         Everton                     7
13          Wolves       Brentford                    14
14   Nott'm Forest         Chelsea                    17
15        West Ham         Ipswich                     9
16       Leicester     Bournemouth                    20
17     Southampton     Bournemouth                    20
18         Man Utd     Aston Villa                     8
19         Ipswich        West Ham                    20

    mean team Goal scored all  opp mean team Goal scored all
0                         3.0                            1.4
1                         2.6                            1.8
2                         2.2                            1.4
3                         2.2                            1.2
4                         2.2                            1.4
5                         2.2                            1.0
6                         2.0                            1.8
7                         1.8                            1.6
8                         1.8                            2.0
9                         1.8                            2.6
10                        1.8                            1.2
11                        1.6                            1.8
12                        1.4                            2.2
13                        1.4                            2.2
14                        1.4                            3.0
15                        1.4                            1.0
16                        1.4                            1.8
17                        1.2                            1.8
18                        1.0                            2.2
19                        1.0                            1.4



GW7
20
              team        opponent  last_season_position  \
0          Chelsea         Man Utd                     6
1         Man City     Bournemouth                     1
2          Arsenal       Newcastle                     2
3          Everton     Southampton                    15
4      Aston Villa           Spurs                     4
5            Spurs     Aston Villa                     5
6        Liverpool        Brighton                     3
7        Brentford          Fulham                    16
8      Bournemouth        Man City                    12
9         Brighton       Liverpool                    11
10          Fulham       Brentford                    13
11       Leicester         Ipswich                    20
12  Crystal Palace          Wolves                    10
13       Newcastle         Arsenal                     7
14        West Ham   Nott'm Forest                     9
15          Wolves  Crystal Palace                    14
16   Nott'm Forest        West Ham                    17
17     Southampton         Everton                    20
18         Ipswich       Leicester                    20
19         Man Utd         Chelsea                     8

    mean team Goal scored all  opp mean team Goal scored all
0                    2.666667                       0.833333
1                    2.500000                       2.000000
2                    2.333333                       1.333333
3                    2.166667                       1.166667
4                    2.166667                       2.000000
5                    2.000000                       2.166667
6                    2.000000                       1.666667
7                    2.000000                       1.666667
8                    2.000000                       2.500000
9                    1.666667                       2.000000
10                   1.666667                       2.000000
11                   1.666667                       1.000000
12                   1.666667                       1.333333
13                   1.333333                       2.333333
14                   1.333333                       1.166667
15                   1.333333                       1.666667
16                   1.166667                       1.333333
17                   1.166667                       2.166667
18                   1.000000                       1.666667
19                   0.833333                       2.666667



GW8
20
              team        opponent  last_season_position  \
0         Man City     Bournemouth                     1
1          Chelsea         Man Utd                     6
2          Arsenal       Newcastle                     2
3            Spurs     Aston Villa                     5
4         Brighton       Liverpool                    11
5        Brentford          Fulham                    16
6        Liverpool        Brighton                     3
7          Everton     Southampton                    15
8      Aston Villa           Spurs                     4
9      Bournemouth        Man City                    12
10          Fulham       Brentford                    13
11        West Ham   Nott'm Forest                     9
12  Crystal Palace          Wolves                    10
13       Leicester         Ipswich                    20
14          Wolves  Crystal Palace                    14
15       Newcastle         Arsenal                     7
16     Southampton         Everton                    20
17   Nott'm Forest        West Ham                    17
18         Ipswich       Leicester                    20
19         Man Utd         Chelsea                     8

    mean team Goal scored all  opp mean team Goal scored all
0                    2.428571                       1.714286
1                    2.428571                       0.714286
2                    2.428571                       1.142857
3                    2.000000                       1.714286
4                    1.857143                       1.857143
5                    1.857143                       1.714286
6                    1.857143                       1.857143
7                    1.857143                       1.142857
8                    1.714286                       2.000000
9                    1.714286                       2.428571
10                   1.714286                       1.857143
11                   1.428571                       1.142857
12                   1.428571                       1.285714
13                   1.285714                       0.857143
14                   1.285714                       1.428571
15                   1.142857                       2.428571
16                   1.142857                       1.857143
17                   1.142857                       1.428571
18                   0.857143                       1.285714
19                   0.714286                       2.428571



GW9
20

In [14]:
data[pd.isna(data["opp mean team Goal scored all"])]["GW"].value_counts()

GW
1    670
Name: count, dtype: int64

In [15]:
data[pd.isna(data["opp mean team Goal scored all"])]. shape

(670, 122)

In [16]:
data[pd.isna(data["opp mean team Goal scored all"])]["GW"].value_counts()

GW
1    670
Name: count, dtype: int64

In [17]:
data_gw[pd.isna(data_gw["opp mean team Goal scored all"])]["opponent"].value_counts()

Series([], Name: count, dtype: int64)

In [18]:
data_gw[data_gw["opponent"]=="Crystal Palace"][["name","team"]]

                                 name    team
277                        Alfie Pond  Wolves
287       Carlos Roberto Forbs Borges  Wolves
348      André Trindade da Costa Neto  Wolves
350                  Bastien Meupiyou  Wolves
356                       Luke Cundle  Wolves
357                  Hugo Bueno López  Wolves
358                    Santiago Bueno  Wolves
359                    Saša Kalajdžić  Wolves
361                   Boubacar Traoré  Wolves
365               José Malheiro de Sá  Wolves
366             Rodrigo Martins Gomes  Wolves
368                     Nathan Fraser  Wolves
369              Nélson Cabral Semedo  Wolves
371                     Enso González  Wolves
375    Francisco Jorge Tomás Oliveira  Wolves
376                     Pablo Sarabia  Wolves
377            Daniel Castelo Podence  Wolves
378                    Daniel Bentley  Wolves
379                      Matt Doherty  Wolves
380                       Fábio Silva  Wolves
381             Pedro Cardoso de Lima  Wolves
382  Matheus Santos Carneiro Da Cunha  Wolves
383                      Craig Dawson  Wolves
384                   Rayan Aït-Nouri  Wolves
387                      Leon Chiwome  Wolves
388                      Mario Lemina  Wolves
389   Gonçalo Manuel Ganchinho Guedes  Wolves
390                    Hwang Hee-chan  Wolves
395                Toti António Gomes  Wolves
396                         Joe Hodge  Wolves
397                   Yerson Mosquera  Wolves
398                    Ki-Jana Hoever  Wolves
401                          Tom King  Wolves
406        João Victor Gomes da Silva  Wolves
407              Jørgen Strand Larsen  Wolves
408            Jean-Ricner Bellegarde  Wolves
409                       Tommy Doyle  Wolves
414                   Tawanda Chirewa  Wolves
455                     Sam Johnstone  Wolves